### ISSUE TITLE
Hunter - PC attack and Pet attack with LoS (vertical)

### ISSUE THREAD

**Issue by jichael2** [Nextcalibur/Bugtracker#504]
https://youtu.be/LyhoXDaS0vU 

video says it all. 

Issue 1. can´t send a pet to attack on tabbed target down the hill. but works fine on level ground. 
Issue 2. cant attack mob on lower level ground. weird LoS. can´t send pet on it either.

edit. sidenote : do note the amount of gold I got. 7.5 g reward  for tossing some torches in town @level 10.

**Comment by Nextcalibur** [comment]
Fixed the quest reward, Line of Sight needs a bit of rework we have noticed it's not working optimal in uneven terrain.

**Comment by Nextcalibur** [comment]
Looking at the video that's perfectly normal LoS until you get closer.

**Comment by tonine-entro** [comment]
Pet attack with LOS not fixed for warlock and hunter pet.
https://cdn.discordapp.com/attachments/677454223155134464/733001957865947176/Untitled.mp4

**Comment by Nextcalibur** [comment]
Send pet fixed. Now behaves like the video above ^
