### ISSUE TITLE
[NPC][Ability] Loch Modan

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#506]
https://classic.wowhead.com/npc=1167/stonesplinter-digger#abilities
Missing sunder armor https://tbcdb.com/?npc=1167#abilities 

https://classic.wowhead.com/npc=1165/stonesplinter-geomancer#abilities
https://vanillawowdb.com/?spell=11829 missing, this is the spell I found on different source.

https://classic.wowhead.com/npc=1179/mogrosh-enforcer#abilities
Missing https://classicdb.ch/?spell=13532

https://tbcdb.com/?npc=1181#abilities  & https://tbcdb.com/?npc=1205#abilities
https://tbcdb.com/?spell=3229

https://tbcdb.com/?npc=1175#abilities
Sunder Armor missing  https://tbcdb.com/?npc=1175#abilities

https://tbcdb.com/?npc=1195#abilities
https://tbcdb.com/?spell=744

**Comment by Nextcalibur** [comment]
Fixed Stonsplinter Digger. Incorrect Spell ID in creature script.

**Comment by Nextcalibur** [comment]
Fixed Stonesplinter Geomancer

**Comment by Bart748** [comment]
Updated Sunder on Stonesplinter Digger
Added Ability Thunderclap to Mo'grosh Enforcer
Updated Castflag on Mo'grosh Shaman Quick Bloodlust spell
Updated Castflag on Grawmug Quick Bloodlust
Updated Castflag on Tunnel Rat Digger Sunder Armor
Updated Forest Lurker Poison, on spawn self spell to offensive spell

**Comment by Megalomaniac6** [comment]
Sunder on Stonesplinter Digger - still not working
Mo'grosh Shaman Quick Bloodlust spell - still not working
Grawmug Quick Bloodlust - could not find npc Grawmug. Discard entry.
Tunnel Rat Digger Sunder Armor - still not working
Forest Lurker Poison, on spawn self spell to offensive spell - still not working
