### ISSUE TITLE
[NPC] [PVP] Item vendors Lieutenant Tristia & Doris Volanthius

### ISSUE THREAD

**Issue by DivineKofa** [Nextcalibur/Bugtracker#675]
Currently the Alliance and Horde vendors which should be selling PvP offset items in exchange of honor and battleground marks are missing from the game. 

https://tbcdb.com/?npc=24520
https://tbcdb.com/?npc=23446

**Comment by Azelen** [comment]
Should be fixed on next server restart.

**Comment by DivineKofa** [comment]
Doris Volanthius is currently present in the Hall of Legends, while Lieutenant Tristia is still missing from the Champions' Hall.
